# Generated by Django 5.0.6 on 2024-07-01 15:23

import django.db.models.deletion
import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=100)),
                ('IMAGE', models.ImageField(blank=True, null=True, upload_to=shop.models.getFileName)),
                ('DESCRIPTION', models.TextField(max_length=500)),
                ('STATUS', models.BooleanField(default=False, help_text='0-show,1-Hidden')),
                ('CREATE', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=100)),
                ('VENDOR', models.CharField(max_length=100)),
                ('PRODUCT_IMAGE', models.ImageField(blank=True, null=True, upload_to=shop.models.getFileName)),
                ('QUANTITY', models.IntegerField()),
                ('ORIGINAL_PRICE', models.FloatField()),
                ('SELLING_PRICE', models.FloatField()),
                ('DESCRIPTION', models.TextField(max_length=500)),
                ('STATUS', models.BooleanField(default=False, help_text='0-show,1-Hidden')),
                ('TRENDING', models.BooleanField(default=False, help_text='0-default,1-Trending')),
                ('CREATE', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
        ),
    ]
