# Generated by Django 5.0.6 on 2024-07-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='CREATED_AT',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
